In [3]:
import numpy as np

In [26]:
B = np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

In [27]:
B

array([[ 1, -1,  1,  3],
       [ 2,  1,  8, 18],
       [ 4,  2, -3, -2]])

In [28]:
A = B.astype(np.float64)

In [29]:
A

array([[ 1., -1.,  1.,  3.],
       [ 2.,  1.,  8., 18.],
       [ 4.,  2., -3., -2.]])

In [30]:
m = A.shape[0]

In [31]:
n = A.shape[1]

In [32]:
m, n

(3, 4)

In [33]:
#Row Addition & Substraction Function

In [34]:
def row_add(A, n, row1, row2):
    for i in range(n):
        A[row1][i] += A[row2][i]
    return A

In [35]:
def row_subtract(A, n, row1, row2):
    for i in range(n):
        A[row1][i] -= A[row2][i]
    return A

In [36]:
#Scalar Mutliplication Function

In [37]:
def scalar_multiply(A, n, row, scalar):
    for i in range(n):
        A[row][i] *= scalar
    return A

In [38]:
#Row Swapping Function

In [39]:
def row_swap(A, n, row1, row2):
    for i in range(n):
        temp = A[row1][i]
        A[row1][i] = A[row2][i]
        A[row2][i] = temp
    return A

In [40]:
A

array([[ 1., -1.,  1.,  3.],
       [ 2.,  1.,  8., 18.],
       [ 4.,  2., -3., -2.]])

In [41]:
A = scalar_multiply(A, n, 1, 2)

In [42]:
A

array([[ 1., -1.,  1.,  3.],
       [ 4.,  2., 16., 36.],
       [ 4.,  2., -3., -2.]])

In [43]:
A = row_subtract(A, n, 2, 1)

In [44]:
A

array([[  1.,  -1.,   1.,   3.],
       [  4.,   2.,  16.,  36.],
       [  0.,   0., -19., -38.]])

In [45]:
A = scalar_multiply(A, n, 0, 4)

In [46]:
A

array([[  4.,  -4.,   4.,  12.],
       [  4.,   2.,  16.,  36.],
       [  0.,   0., -19., -38.]])

In [47]:
A = row_subtract(A, n, 1, 0)

In [48]:
A

array([[  4.,  -4.,   4.,  12.],
       [  0.,   6.,  12.,  24.],
       [  0.,   0., -19., -38.]])

In [50]:
x3 = A[2][2] / A[2][3]

In [51]:
x3

0.5

In [52]:
x2 = (A[1][3] - (A[1][2] * x3)) / A[1][1]

In [53]:
x2

3.0

In [54]:
x1 = (A[0][3] - A[0][1] * x2 - A[0][2] * x3) / A[0][0]

In [55]:
x1

5.5