In [3]:
import numpy as np

In [64]:
B = np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

In [65]:
B

array([[ 1, -1,  1,  3],
       [ 2,  1,  8, 18],
       [ 4,  2, -3, -2]])

In [66]:
A = B.astype(np.float64)

In [67]:
A

array([[ 1., -1.,  1.,  3.],
       [ 2.,  1.,  8., 18.],
       [ 4.,  2., -3., -2.]])

In [50]:
m = A.shape[0]

In [51]:
n = A.shape[1]

In [52]:
m, n

(3, 4)

In [53]:
#Row Addition & Substraction Function

In [68]:
def row_add(A, n, row1, row2):
    for i in range(n):
        A[row1][i] += A[row2][i]
    return A

In [69]:
def row_subtract(A, n, row1, row2):
    for i in range(n):
        A[row1][i] -= A[row2][i]
    return A

In [70]:
#Scalar Mutliplication Function

In [71]:
def scalar_multiply(A, n, row, scalar):
    for i in range(n):
        A[row][i] *= scalar
    return A

In [72]:
#Row Swapping Function

In [73]:
def row_swap(A, n, row1, row2):
    for i in range(n):
        temp = A[row1][i]
        A[row1][i] = A[row2][i]
        A[row2][i] = temp
    return A

In [74]:
A

array([[ 1., -1.,  1.,  3.],
       [ 2.,  1.,  8., 18.],
       [ 4.,  2., -3., -2.]])

In [75]:
A = scalar_multiply(A, n, 1, 2)

In [76]:
A

array([[ 1., -1.,  1.,  3.],
       [ 4.,  2., 16., 36.],
       [ 4.,  2., -3., -2.]])

In [77]:
A = row_subtract(A, n, 2, 1)

In [78]:
A

array([[  1.,  -1.,   1.,   3.],
       [  4.,   2.,  16.,  36.],
       [  0.,   0., -19., -38.]])

In [80]:
A = scalar_multiply(A, n, 0, 4)

In [81]:
A

array([[  4.,  -4.,   4.,  12.],
       [  4.,   2.,  16.,  36.],
       [  0.,   0., -19., -38.]])

In [82]:
A = row_subtract(A, n, 1, 0)

In [83]:
A

array([[  4.,  -4.,   4.,  12.],
       [  0.,   6.,  12.,  24.],
       [  0.,   0., -19., -38.]])