In [2]:
import numpy as np

In [81]:
B = np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

In [82]:
A = np.copy(B).astype('float64')

In [83]:
A

array([[ 1., -1.,  1.,  3.],
       [ 2.,  1.,  8., 18.],
       [ 4.,  2., -3., -2.]])

In [72]:
m = A.shape[0]

In [73]:
n = A.shape[1]

In [74]:
m, n

(3, 4)

In [84]:
A

array([[ 1., -1.,  1.,  3.],
       [ 2.,  1.,  8., 18.],
       [ 4.,  2., -3., -2.]])

In [54]:
#Multiply 1st with 2 and subtract it from 2nd

In [85]:
for i in range(n):
    A[1][i] -= A[0][i]*2 

In [86]:
A

array([[ 1., -1.,  1.,  3.],
       [ 0.,  3.,  6., 12.],
       [ 4.,  2., -3., -2.]])

In [47]:
#multiply 1st row with 4 and subtract it from 3rd

In [87]:
for i in range(n):
    A[2][i] -= A[0][i]*4 

In [88]:
A

array([[  1.,  -1.,   1.,   3.],
       [  0.,   3.,   6.,  12.],
       [  0.,   6.,  -7., -14.]])

In [ ]:
#multiply 2st row with 2 and subtract it from 3rd

In [89]:
for i in range(n):
    A[2][i] -= A[1][i]*2

In [90]:
A

array([[  1.,  -1.,   1.,   3.],
       [  0.,   3.,   6.,  12.],
       [  0.,   0., -19., -38.]])

In [91]:
#multiply 2nd row with 1/3

In [92]:
for i in range(n):
    A[1][i] *= 1/3

In [93]:
A

array([[  1.,  -1.,   1.,   3.],
       [  0.,   1.,   2.,   4.],
       [  0.,   0., -19., -38.]])

In [94]:
#multiply 3rd row with 1/19

In [95]:
for i in range(n):
    A[2][i] *= 1/19

In [96]:
A

array([[ 1., -1.,  1.,  3.],
       [ 0.,  1.,  2.,  4.],
       [ 0.,  0., -1., -2.]])