In [1]:
import numpy as np

In [2]:
A = np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

In [3]:
A

array([[ 1, -1,  1,  3],
       [ 2,  1,  8, 18],
       [ 4,  2, -3, -2]])

In [4]:
A.transpose()

array([[ 1,  2,  4],
       [-1,  1,  2],
       [ 1,  8, -3],
       [ 3, 18, -2]])

In [6]:
I4 = np.eye(4)

In [7]:
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
r = np.random.randint(-10,50,size=(4,4))

In [11]:
r

array([[43, 26, 23, 15],
       [42, 24, 15,  6],
       [18, 14, 38, 37],
       [18, -4, 28, -5]])