In [3]:
import numpy as np

In [14]:
A = np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2], [12, 6, 23, 45]])

In [5]:
A

array([[ 1, -1,  1,  3],
       [ 2,  1,  8, 18],
       [ 4,  2, -3, -2]])

In [6]:
A.transpose()

array([[ 1,  2,  4],
       [-1,  1,  2],
       [ 1,  8, -3],
       [ 3, 18, -2]])

In [7]:
I4 = np.eye(4)

In [8]:
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
r = np.random.randint(-10,50,size=(4,4))

In [10]:
r

array([[40, 15, -4, 41],
       [ 9, 14, -8, 49],
       [21,  4, 33, 37],
       [-9, 45, -5,  6]])

In [12]:
A

array([[ 1, -1,  1,  3],
       [ 2,  1,  8, 18],
       [ 4,  2, -3, -2]])

In [15]:
np.linalg.det(A)

740.9999999999998